llm: ${sub|text_res}
tools:
 - name: GeneralOD    
   url: http://10.0.0.132:8005/inf_predict
 - name: SuperResolution
   model_id: CompVis/ldm-super-resolution-4x-openimages
 - name: TavilyWebSearch
   tavily_api_key: ${env|tavily_api_key, null}